#Project 1 by Dabelu Okigbo




import random

# ASCII art Sourced from github user wynand1004
rock = """
    _______
---'   ____)
      (_____)
      (_____)
      (____)
---.__(___)
"""

paper = """
     _______
---'    ____)____
           ______)
          _______)
         _______)
---.__________)
"""

scissors = """
    _______
---'   ____)____
          ______)
       __________)
      (____)
---.__(___)
"""

# The following function takes in a move as a parameter.
# It will return the corresponding string art based on the move.
"""
e.g: 
    move = "rock"
    moveArt = printMove(move)
    print(moveArt)
    # will print the rock hand as shown below
        _______
    ---'   ____)
          (_____)
          (_____)
          (____)
    ---.__(___)


"""


def printMove(move):
    if move == 'rock':
        return rock
    if move == 'paper':
        return paper
    if move == 'scissors':
        return scissors


########---------------------DABELU--PLAYER--FUNCTION------------------########


# The following function takes in the playerName as a parameter.
# The function will return the playerMove as a string
"""
e.g: 
    playerName = "Alex"
    makePlayerMove(playerName)

    # the following would get printed

    Choose rock, paper, or scissors: 
    rock

    Alex chose: 
            _______
        ---'   ____)
              (_____)
              (_____)
              (____)
        ---.__(___)

"""


# Player Function that prints player name and their choice
def makePlayerMove(playerName):
    # When code is executed and the function is called
    # from main method, the system asks the user to make their move
    playerMove = input("Choose rock, paper, or scissors: ")

    # Whatever the user enters, the system makes the user input lower case
    playerMove = playerMove.lower()

    # the printMove function is called and
    # assigns the graphic with the user input
    playerArt = printMove(playerMove)

    # after user makes their choice, system prints the player name and their selection
    print(playerName, "chose: ")

    # The system prints the move graphic associated with the player choice
    print(playerArt)

    # the system returns the playerMove fucntion output
    return playerMove


########--------------------------END----------------------------------########


########-----------------DAWIT--COMPUTER--FUNCTION---------------------########


# The following function takes in the computerName as a parameter.
# The function will return the computerMove as a string
"""
e.g: 
    computerName = "Eric"
    makeComputerMove(computerName)

    # for this example, we will say the random number drawn was 1, so the following will get printed

    Eric chose: 
            _______
        ---'   ____)
              (_____)
              (_____)
              (____)
        ---.__(___)

"""
# A new variable is assigned to a string that contains the choice for the game
computerOptions = "rock, paper, scissors"

# The assigned string is split at the comma to create a list
computerChoices = computerOptions.split(", ")


# Computer Function that randomly chooses rock, paper, or scissors for the computer
def makeComputerMove(computerName):
    # A new variable is assigned to a string that contains the choice for the game
    # computerOptions = "rock, paper, scissors"

    # A new variable is assigned to the random choice computer makes from the list
    computerMove = random.choice(computerChoices)

    # A new variable that associates computer choice with the graphic art
    computerArt = printMove(computerMove)

    # The system prints computer name entered by the user and computer random choice generated by "computerMove" variable
    print(computerName, "chose: ")

    # The system prints the move graphic associated with the computer choice
    print(computerArt)

    # The system returns the choice made by the computer
    return computerMove


########--------------------------END----------------------------------########


########---------------ZEESHAWN--CHECK--ROUND--WINNER------------------########

# Game Rules: Paper trumps Rock, Rock trumps Scissors, and Scissors trumps Paper.

# The following function takes in the playerMove and computerMove as parameters and returns the winner as a string.
def checkRoundWinner(playerMove, computerMove):
    # Conditional statements where it checks playerMove vs ComputerMove and decides the winner
    if playerMove == "rock" and computerMove == "scissors":
        return ("Player Won")
    elif computerMove == "rock" and playerMove == "scissors":
        return ("Computer Won")
    elif playerMove == "rock" and computerMove == "paper":
        return ("Computer Won")
    elif computerMove == "rock" and playerMove == "paper":
        return ("Player Won")
    elif computerMove == "scissors" and playerMove == "paper":
        return ("Computer Won")
    elif playerMove == "scissors" and computerMove == "paper":
        return ("Player Won")
    # if none of the above statements are true then system returns "Tie"
    else:
        return ("Tie")

    # Returns the Round Winner
    return roundWinner


########--------------------------END----------------------------------########


# The main function will be the main driver for your game of rock, paper, scissors.
# We want the game to continue until either the player or the computer wins the best out of three.
# *Hint: a while loop might be helpful :)*


########-----------------------MAIN--METHOD----------------------------########

# Main method where all program functions are called to play the game
def main():
    # User/player prompt to enter their name
    playerName = input("Enter Name of player: ")

    # if player does not enter anything, the program re-runs the main method prompting user to enter their name
    if playerName == "":
        main()

    # User prompt to enter computer name
    computerName = input("Enter Name of computer: ")

    # Program continously prompts the user to enter computer name if no name is detected
    if computerName == "":
        print("Name is required")
        computerName = input("Enter Name of computer: ")

    # Score Variables
    playerWins = 0
    computerWins = 0

    # An unknown number of loops statement that keeps playing the game until a winner is declared; best 2 out of 3.
    while True:

        # A new variable assigned that calls two functions: makePlayerMove and makeComputerMove functions and determines
        # the winner with the third function "checkRoundWinner"
        roundWinner = checkRoundWinner(makePlayerMove(playerName), makeComputerMove(computerName))

        # Conditional statements that validate who won the round and assigns a point of 1 to the winner
        if roundWinner == "Player Won":
            print(playerName, "won the round!")
            playerWins += 1
        elif roundWinner == "Computer Won":
            print(computerName, "wins the round!")
            computerWins += 1

        # if no one wins, the round ends in a "Tie"
        else:
            print("It was a tie!")

        # if the player wins two out of three games, they win the match and program ends
        if playerWins == 2:
            print(playerName, "won this match!")
            break

        # if the computer wins two out of three games, they win the match and program ends
        if computerWins == 2:
            print(computerName, "won this match!")
            break


########--------------------------END----------------------------------########


# Call main method
main()